### ISSUE TITLE
Will there be an equivalent for go?

### ISSUE THREAD

**Issue by seanyu4296** [DataDog/dd-opentelemetry-exporter-js#13]
Hi, i am not sure if this should be here. Posting it here to get visibility

@ericmustin will there be a `dd-opentelemetry-exporter-go`? asking because our org that heavily uses datadog is looking into using OpenTelemetry standards? :)

**Comment by ericmustin** [comment]
no worries, at this time we don't have plans to, we are working on OTLP support in the datadog-agent instead.
